server:
  port: 6002

spring:
  application:
    name: rocketmq-producer

#rocketmq:
#  name-server: 192.168.85.128:9876
#  producer:
#    group: my-group1
#    sendMessageTimeout: 300000
#    # default producer tls config
#    tls-enable: false
#
## properties used in the application
#demo:
#  rocketmq:
#    topic: string-topic
#    orderTopic: order-paid-topic
#    msgExtTopic: message-ext-topic
#    transTopic: spring-transaction-topic
#    topic.user: user-topic
#
#    bytesRequestTopic: bytesRequestTopic-tagA
#    stringRequestTopic: stringRequestTopic-tagA
#    objectRequestTopic: objectRequestTopic-tagA
#    genericRequestTopic: genericRequestTopic-tagA
#
#    extNameServer: 127.0.0.1:9876
#
#    # self ext producer tls config
#    ext.useTLS: false
    
rocketmq: 
  name-server: 192.168.85.128:9876
  # When set rocketmq.pull-consumer.group and rocketmq.pull-consumer.topic, rocketmqTemplate will start lite pull consumer
  # If you do not want to use lite pull consumer, please do not set rocketmq.pull-consumer.group and rocketmq.pull-consumer.topic
  pull-consumer: 
    group: my-group1
    topic: test
  # default LitePullConsumer TLS
    tlsEnable: false
demo: 
  rocketmq: 
    topic: string-topic
    bytesRequestTopic: bytesRequestTopic
    stringRequestTopic: stringRequestTopic
    objectRequestTopic: objectRequestTopic
    genericRequestTopic: genericRequestTopic
    bytesRequestConsumer: bytesRequestConsumer
    stringRequestConsumer: stringRequestConsumer
    objectRequestConsumer: objectRequestConsumer
    genericRequestConsumer: genericRequestConsumer
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic
    user: user-topic
    tag: tagA
    # another nameserver different global
    myNameServer: 127.0.0.1:9876
    # my Consumer TLS Listener
    tlsEnable: false

# ext rocketmq consumer template TLS
  ext:
    consumer:
      tlsEnable: false
