server:
  port: 6001

spring:
  application:
    name: rocketmq-producer

rocketmq:
  name-server: 192.168.85.128:9876
  producer:
    group: my-group1
    sendMessageTimeout: 300000

# properties used in the application
demo:
  rocketmq:
    topic: string-topic
    orderTopic: order-paid-topic
    msgExtTopic: message-ext-topic
    transTopic: spring-transaction-topic
    topic.user: user-topic

    bytesRequestTopic: bytesRequestTopic-tagA
    stringRequestTopic: stringRequestTopic-tagA
    objectRequestTopic: objectRequestTopic-tagA
    genericRequestTopic: genericRequestTopic-tagA

    extNameServer: 127.0.0.1:9876

    # self ext producer tls config
    ext.useTLS: false