server:
  port: 6001

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
         # uri: git@github.com:yuanpong/spring-cloud-config.git
          uri: https://github.com/yuanpong/spring-cloud-config.git
          #搜索目录
          search-paths:
            - spring-cloud-config
          #读取分支
          label: main
          #忽略SSL验证
          skip-ssl-validation: true
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver8011.com:8011/eureka,http://eurekaserver8012.com:8012/eureka
  instance:
    instance-id: config-server-6001
    prefer-ip-address: true
    #Eureka 客户端向服务端发送心跳的时间间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 10
    #Eureka 服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 20